# Generated by Django 5.0.6 on 2024-05-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerates',
            name='daily_change',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='exchangerates',
            name='date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='exchangerates',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
