# Generated by Django 5.0.6 on 2024-05-29 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency_module', '0002_alter_exchangerates_daily_change_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CountryCurrencies',
            new_name='CountryCurrency',
        ),
    ]
